{
  "hash": "efee229c07f0ad63b89a6a0e49c4d736",
  "result": {
    "markdown": "---\ntitle: \"Final Blog\"\nauthor: \"Hayden Beyer\"\nlisting:\n  contents: posts\n  sort: \"date desc\"\n  type: default\n  categories: true\n  sort-ui: false\n  filter-ui: false\npage-layout: full\ntitle-block-banner: true\n---\n\n\n\n## Abstract\n- The Himalayan Database is a detailed archive documenting mountaineering expeditions in the  Himalayans. This data details the peaks, expeditions, climbing statuses, and geographic information of numerous Himalayan summits. I will explore these data in two tidy tibbles, making it easier to analyze trends in mountaineering expeditions, including seasonality, success rates, and national participation over time. To manage size, the expeditions file was filtered down to the recent years of 2020-2024.\n\n# Data Read\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nexped_tidy <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-01-21/exped_tidy.csv')\npeaks_tidy <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-01-21/peaks_tidy.csv')\n# peaks_tidy$PKNAME\n# mean(peaks_tidy$HEIGHTM)\n# mean(peaks_tidy$HEIGHTF)\n```\n:::\n\n\n\n# Expedition Deaths\n- Are expeditions without hired personnel more dangerous?\n\n::: {.cell}\n\n```{.r .cell-code}\nhired_deaths <- exped_tidy |>\n  mutate(\n    any_death = (HDEATHS + MDEATHS) > 0,\n    hired_status = if_else(NOHIRED == TRUE, \"No Hired Personnel\", \"Hired Personnel\")\n  ) |>\n  group_by(hired_status) |>\n  summarise(\n    total_expeditions = n(),\n    expeditions_with_death = sum(any_death, na.rm = TRUE),\n    death_rate = expeditions_with_death / total_expeditions\n  )\n\nggplot(hired_deaths, aes(x = hired_status, y = death_rate, fill = hired_status)) +\n  geom_col(width = 0.5, show.legend = FALSE) +\n  scale_y_continuous(\n    labels = scales::percent_format(),\n    limits = c(0, 0.08)\n  ) +\n  scale_fill_manual(values = c(\"Hired Personnel\" = \"blue\", \"No Hired Personnel\" = \"red\")) +\n  labs(\n    title = \"Death Rates With and Without Hired Personnel\",\n    x = NULL,\n    y = \"% of Expeditions with a Death\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# AI was used to figure out how to scale the y axis in percent format: Question - \"What syntax do you use to add percents to y axis\"\n```\n:::\n\n- Expeditions with Hired Personnel have a death rate of 4.8%, which is more than double the 2.1% rate seen in expeditions with No Hired Personnel. However, there is a significant difference in the total number of expeditions between the two groups. There were 736 expeditions with hired staff compared to only 146 without. This suggests that the majority of expeditions rely on professional support. While the percentage is higher for hired expeditions, this does not necessarily mean hired staff make an expedition more dangerous, but rather it may display that hired personnel are typically used for more difficult, higher-altitude, or higher-risk peaks (like Everest) where self done expeditions might have lower risk.\n\n\n# Death Heatmaps\n- Is there a correlation between the number of deaths among hired staff versus expedition members, and which group typically has a higher mortality?\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths_df <- exped_tidy |>\n  group_by(HDEATHS, MDEATHS) |>\n  summarise(no_deaths = n(), .groups = \"drop\") |>\n  mutate(\n    HDEATHS = factor(HDEATHS),\n    MDEATHS = factor(MDEATHS)\n  )\n\nggplot(deaths_df, aes(x = HDEATHS, y = MDEATHS, fill = no_deaths)) +\n  geom_tile(colour = \"darkgray\", linewidth = 0.8) +\n  geom_text(aes(label = no_deaths), colour = \"gray\", fontface = \"bold\", size = 4) +\n  scale_fill_viridis_c(\n    option = \"plasma\",\n    direction = -1,\n    trans = \"log10\",        \n  ) +\n  labs(\n    title = \"Expedition Fatalities: Hired Staff vs. Members\",\n    x = \"Hired Staff Deaths\",\n    y = \"Member Deaths\",\n    fill = \"# of Exped.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# AI was used in this graph to add log scale. Question: How do I scale this down?\n```\n:::\n\nThe majority of expeditions (844 of 882) result in zero deaths of any kind. Deaths among hired staff and members tend to occur independently. Events with multiple fatalities involving both groups at the same time are extremely rare. Instead, they are usually isolated incidents involving one or two individuals, with expedition members appearing to die at a slightly higher rate in single death scenarios than the hired staff. This makes sense as the hired staff tends to be more prepared and experienced, however, accidents can still happen. \n\n# Joining the datasets for models\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nmodel_df <- exped_tidy |>\n  left_join(peaks_tidy, by = \"PEAKID\") |>\n  mutate(\n    success_binary = factor(ifelse(SUCCESS1, \"Success\", \"Failure\")),\n    O2USED = factor(O2USED),\n    SEASON_FACTOR = factor(SEASON_FACTOR)\n  ) |>\n  filter(!is.na(success_binary)) |> filter(!is.na(success_binary), !is.na(O2USED), !is.na(TOTHIRED)) |>\n  mutate(hired_cat = case_when(\n    TOTHIRED == 0  ~ \"None (0)\",\n    TOTHIRED <= 5  ~ \"Low (1-5)\",\n    TOTHIRED <= 15 ~ \"Medium (6-15)\",\n    TOTHIRED > 15  ~ \"High (15+)\"\n  ),\n  hired_cat = fct_relevel(hired_cat, \"None (0)\", \"Low (1-5)\", \"Medium (6-15)\", \"High (15+)\"))\n```\n:::\n\n\n\n# Probability of Success Base of Hired No. Personel, Peak Height and Oxygen Use. \nHow does the probability of expedition success change as peak height increases, and to what extent do supplemental oxygen and different levels of hired support help the as mountains go to higher elevations?\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nlibrary(broom)\nlibrary(ggeffects)\nlibrary(ggplot2)\n\n\nsuccess_glm <- glm(success_binary ~ HEIGHTM + O2USED + hired_cat, \n                   family = \"binomial\", \n                   data = model_df)\n\n\npreds_success <- ggpredict(success_glm, terms = c(\"HEIGHTM [all]\", \"O2USED\", \"hired_cat\")) |>\n  as.data.frame()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = preds_success, aes(x = x, y = predicted)) + \n  geom_line(aes(colour = group), linewidth = 1.5) + \n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group), alpha = 0.3) + \n  geom_jitter(data = model_df, \n              aes(x = HEIGHTM, y = as.numeric(success_binary) - 1, colour = O2USED), \n              width = 0, height = 0.04, alpha = 0.3) + \n  facet_wrap(~ facet) + \n  scale_colour_viridis_d() + \n  scale_fill_viridis_d() +\n  theme_minimal() +\n  labs(x = \"Peak Height (m)\", y = \"Probability of Success\", colour = \"Oxygen Used\", fill = \"Oxygen Used\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nIn every scenario, the probability of success drops as Peak Height increases. This drop is most apparent for climbers not using supplemental oxygen (the dark purple lines). Comparing the four facets, None (0), Low (1-5), Medium (6-15), and High (15+), shows that increasing the number of hired personnel flattens the curve going down. It is interesting to point out that with High (15+) hired support, those not using oxygen still have a higher success rate at around 8,000 meters than those with no support at the same height. Generally speaking the gap between oxygen users and non users only really becomes a critical point as expeditions move into the death zone (above 7,500–8,000 meters).\n\n\n# GLM Probability of Success\n- When accounting for geography, equipment, staffing, and timing, what are the main drivers of mountaineering success, and which predictors show the greatest risk of failure?\n\n::: {.cell}\n\n```{.r .cell-code}\nsuccess_glm <- glm(success_binary ~ HEIGHTM + O2USED + hired_cat + SEASON_FACTOR + TOTMEMBERS, \n                   family = \"binomial\", \n                   data = model_df)\n\nprint(success_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = success_binary ~ HEIGHTM + O2USED + hired_cat + \n    SEASON_FACTOR + TOTMEMBERS, family = \"binomial\", data = model_df)\n\nCoefficients:\n           (Intercept)                 HEIGHTM              O2USEDTRUE  \n              6.827713               -0.001049                2.908885  \n    hired_catLow (1-5)  hired_catMedium (6-15)     hired_catHigh (15+)  \n              0.650175                0.993114                1.864657  \n   SEASON_FACTORSpring     SEASON_FACTORSummer     SEASON_FACTORWinter  \n              0.043211                0.151672               -0.717079  \n            TOTMEMBERS  \n              0.041194  \n\nDegrees of Freedom: 881 Total (i.e. Null);  872 Residual\nNull Deviance:\t    1066 \nResidual Deviance: 837.4 \tAIC: 857.4\n```\n\n\n:::\n:::\n\n# Model Breakdown\nCoefficients:\n\n- Peak Height (HEIGHTM): The coefficient is negative (-0.001049), which means for every additional meter of peak height, the log-odds of success decrease slightly, which makes sense.\n\n- Oxygen Use (O2USEDTRUE): The strongest positive predictor in the model (2.908885). Using supplemental oxygen increases the log-odds of reaching the summit compared to not using it, which makes sense.\n\n- Hired Support (hired_cat): All levels of hired support show positive coefficients relative to the baseline (None). The effect grows higher as more staff are added, Low is 0.65, Medium is 0.99, and High is 1.86.\n\n- Seasonality (SEASON_FACTOR):Spring (0.043) and Summer (0.15) have positive coefficients, indicating they are more favorable for success than the baseline (Autumn). Winter has a significant negative coefficient (-0.717), identifying it as the most difficult season for success. It is important to note that as previously mentioned summer season is not very popular for hiking which gives a false sense of success. In actuality, Autumn and Spring are the most popular hiking seasons due to their mild climates. \n\n- Team Size (TOTMEMBERS): This has a small positive coefficient (0.041), showing that larger teams may correlate with higher success rates.\n\n# Linear Model\n- Among successful expeditions, which variables significantly increase or decrease the time required to reach the summit?\n\n::: {.cell}\n\n```{.r .cell-code}\nduration_df <- model_df %>%\n  filter(SUCCESS1 == TRUE, SMTDAYS > 0, SMTDAYS < 100)\n\nduration_fit <- lm(SMTDAYS ~ HEIGHTM + CAMPS + ROPE + SEASON_FACTOR, data = duration_df)\n\nduration_fit |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 5\n  term                 estimate std.error statistic      p.value\n  <chr>                   <dbl>     <dbl>     <dbl>        <dbl>\n1 (Intercept)         -25.0      6.16        -4.06  0.0000661   \n2 HEIGHTM               0.00421  0.000952     4.42  0.0000145   \n3 CAMPS                 2.99     0.541        5.52  0.0000000862\n4 ROPE                 -0.00472  0.00403     -1.17  0.243       \n5 SEASON_FACTORSpring   4.60     1.59         2.89  0.00416     \n6 SEASON_FACTORSummer  -1.68     5.20        -0.324 0.746       \n7 SEASON_FACTORWinter  10.6      5.62         1.89  0.0601      \n```\n\n\n:::\n:::\n\n# Model Breakdown\nCoefficients:\n\n- Height of Peak (HEIGHTM) 0.00421: For every 1,000 meters of additional height, the expedition duration increases by about 4.2 days. This is statistically highly significant with a high p value. \n\n- Number of Camps (CAMPS) 2.99: Each additional camp established above base camp adds approximately 3 days to the total expedition time. This is probably for the time needed to transport supplies and acclimate at each new level.\n\n- Seasonality (SEASON_FACTOR): Spring: 4.60 days. Compared to the baseline (Autumn), successful Spring expeditions take about 4.6 days longer.\n- Seasonality (SEASON_FACTOR): Winter: 10.6 days. Compared to the baseline (Autumn), Winter successful climbs take significantly longer 11 extra days. The harsh conditions and limited visibility likely slow the progress.\n- Seasonality (SEASON_FACTOR): Summer: -1.68 days. This is not statistically significant (p=0.746), likely due to the small sample size for summer climbs mentioned in previous data.\n\n\n\n# Conclusion\nMy analysis of Himalayan mountaineering expeditions from 2020–2024 shows and revealed several clear patterns about what separates successful climbs from failed ones, and what makes these mountains so challenging.\n\nLooking on what more I could do. A valuable extension of this work cou be to incorporate the full historical database rather than the 2020–2024 window, which would allow for long term analysis across decades of climbing history. It would also be worth exploring individual peak-level models, since grouping Everest and a 6,000m trekking peak into the same analysis likely hides important differences in what drives success at each level.\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}